// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FluxoCaixa.UnitTests.Lancamentos
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ControleDeFluxoDeCaixaFeature : object, Xunit.IClassFixture<ControleDeFluxoDeCaixaFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Lancamentos.feature"
#line hidden
        
        public ControleDeFluxoDeCaixaFeature(ControleDeFluxoDeCaixaFeature.FixtureData fixtureData, FluxoCaixa_UnitTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Lancamentos", "Controle de Fluxo de Caixa", "  Como usuário do fluxo de caixa \r\n  Quero lançar débitos e créditos\r\n  Para gera" +
                    "r relatórios de saldo diário", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 8
#line hidden
#line 9
   testRunner.Given("usuário \"teste\" está logado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Lançamentos")]
        [Xunit.TraitAttribute("FeatureTitle", "Controle de Fluxo de Caixa")]
        [Xunit.TraitAttribute("Description", "Lançamentos")]
        [Xunit.InlineDataAttribute("150,00", "\"crédito\"", "\"2025-08-14\"", "150,00", new string[0])]
        [Xunit.InlineDataAttribute("200,00", "\"débito\"", "\"2025-08-14\"", "-200,00", new string[0])]
        public void Lancamentos(string valor, string tipo, string data, string resultado, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("valor", valor);
            argumentsOfScenario.Add("tipo", tipo);
            argumentsOfScenario.Add("data", data);
            argumentsOfScenario.Add("resultado", resultado);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Lançamentos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 11
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 12
  testRunner.Given(string.Format("que o valor de lançamento é {0}", valor), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 13
  testRunner.And(string.Format("o tipo do lançamento é {0}", tipo), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 14
  testRunner.When(string.Format("lançar um {0} de R$ {1} em {2}", tipo, valor, data), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 15
  testRunner.Then(string.Format("o valor registrado será {0}", resultado), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 16
  testRunner.And(string.Format("o tipo registrado será {0}", tipo), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 17
  testRunner.And("usuário registrado é \"teste\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 18
  testRunner.And(string.Format("a data será {0}", data), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Valores inválidos")]
        [Xunit.TraitAttribute("FeatureTitle", "Controle de Fluxo de Caixa")]
        [Xunit.TraitAttribute("Description", "Valores inválidos")]
        [Xunit.InlineDataAttribute("\"crédito\"", "0,00", "\"Valor não pode ser zero.\"", new string[0])]
        [Xunit.InlineDataAttribute("\"débito\"", "0,00", "\"Valor não pode ser zero.\"", new string[0])]
        [Xunit.InlineDataAttribute("\"crédito\"", "-1,00", "\"Valor não pode ser negativo.\"", new string[0])]
        [Xunit.InlineDataAttribute("\"débito\"", "-1,00", "\"Valor não pode ser negativo.\"", new string[0])]
        public void ValoresInvalidos(string transacao, string valor, string erro, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("transacao", transacao);
            argumentsOfScenario.Add("valor", valor);
            argumentsOfScenario.Add("erro", erro);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Valores inválidos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 26
   testRunner.When(string.Format("lançar um {0} de R$ {1} em \"2025-08-14\"", transacao, valor), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 27
   testRunner.Then(string.Format("será exibida a mensagem de erro {0}", erro), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Gerar relatório de saldo diário")]
        [Xunit.TraitAttribute("FeatureTitle", "Controle de Fluxo de Caixa")]
        [Xunit.TraitAttribute("Description", "Gerar relatório de saldo diário")]
        public void GerarRelatorioDeSaldoDiario()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Gerar relatório de saldo diário", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 36
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Tipo",
                            "Valor",
                            "Data"});
                table1.AddRow(new string[] {
                            "\"crédito\"",
                            "150,00",
                            "\"2025-08-14\""});
                table1.AddRow(new string[] {
                            "\"débito\"",
                            "50,00",
                            "\"2025-08-13\""});
                table1.AddRow(new string[] {
                            "\"débito\"",
                            "50,00",
                            "\"2025-08-14\""});
                table1.AddRow(new string[] {
                            "\"débito\"",
                            "50,00",
                            "\"2025-08-15\""});
#line 37
  testRunner.Given("que existem os seguintes lançamentos:", ((string)(null)), table1, "Dado ");
#line hidden
#line 43
  testRunner.When("solicitar o saldo consolidado do dia \"2025-08-14\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 44
  testRunner.Then("o saldo consolidado deve ser R$ 100,00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ControleDeFluxoDeCaixaFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ControleDeFluxoDeCaixaFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
